FROM gitpod/workspace-postgres:latest

# Install prereqs
USER root
RUN apt-get update && apt-get install -y \
        libsodium-dev \
    && apt-get clean && rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*

# Setup postgres server for user gitpod
USER gitpod
ENV RACK_ENV=gitpod

USER root
