source 'https://rubygems.org'

gem 'discordrb'
gem 'google-api-client'
gem 'fourchan-kit'
gem 'require_all'
gem 'redd', git: 'https://github.com/avinashbot/redd.git'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'rufus-scheduler'
gem 'tzinfo-data'
gem 'faye-websocket'
gem 'rest-client'
gem 'mini_racer'
gem 'mtg_sdk'
gem 'dotenv'
gem 'debase'
gem 'ruby-debug-ide'
gem 'activerecord'
gem 'sqlite3', '~> 1.3', '< 1.4'
gem 'pg'

group :development do
    gem 'byebug'
end