default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: postgres
  password: postgres
  timeout: 5000

gitpod:
  adapter: postgresql
  user: gitpod
  host: localhost
  database: yuela_dev
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: yuela_dev

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>_cable
    migrations_paths: db/cable_migrate

  cache:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>_queue
    migrations_paths: db/cache_migrate
test:
  <<: *default
  database: yuela_test

docker-compose:
  adapter: postgresql
  host: db
  database: yuela_dev
  user: postgres
  password: postgres
  pool: 5
  timeout: 5000
