default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


gitpod:
  adapter: postgresql
  user: gitpod
  host: localhost
  database: yuela_dev
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: yuela_dev
  pool: 16
  timeout: 5000

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>_cable
  cache:
    <<: *default
    database: <%= ENV['DATABASE_URL'] %>_cache
  queue:
    <<: *default
    database: <%= ENV['DATABASE_URL'] %>_queue


test:
  adapter: postgresql
  database: yuela_test
  pool: 5
  timeout: 5000

docker-compose:
  adapter: postgresql
  host: db
  database: yuela_dev
  user: postgres
  password: postgres
  pool: 5
  timeout: 5000
